# config.yaml

data_path: "F:/frr/data/try_aug"
out_path: "F:/frr/data/try_aug/augment"

# 文件路径配置
input_img_dir: "F:/frr/data/aug_base/split/images/train"
input_label_dir: "F:/frr/data/aug_base/split/labels/train"
output_img_dir: "F:/frr/data/aug_base/aug/images"
output_label_dir: "F:/frr/data/aug_base/aug/labels"

# 增广次数，所有图片同样次数
augment_count: 3

#自动判断
auto: False

category_map:
  weed: [2]
  crop: [0]
  negweed: [1]

# 增广操作设置
augmentation_operations:
  Affine:
    #rotate: [0,0]
    shear: 0.3 # 剪切角度
    scale: [0.9,1.1] #剪切规模
    translate_percent: [0.05,0.05]
    fill: [114,114,114]
    p: 0.5  #概率
  Perspective:
    scale: [0.0, 0.005]   #投影映射
    p: 0.5  #概率
  ShiftScaleRotate:
    shift_limit: 0.1  # 水平和垂直方向平移的最大幅度
    scale_limit: 0.2   #缩放比例限制上下百分比
    rotate_limit: 0 # 旋转的最大角度
    p: 0.5  #概率
  RandomBrightnessContrast:
    brightness_limit: 0.2  #亮度范围上下百分比
    contrast_limit: 0.2 #对比度范围上下百分比
    p: 0.5  #修改概率
  HueSaturationValue:
    hue_shift_limit: 10 #随机调整色调范围
    sat_shift_limit: 15 #饱和度范围
    val_shift_limit: 20 #亮度范围
    p: 0.5
  GaussNoise:
    std_range: [0.1, 0.4] #高斯噪声标准范围，影响清晰度
    p: 0.2
  MotionBlur:
    blur_limit: 3 #运动模糊，值越大越模糊
    p: 0.2
  CoarseDropout:
    num_holes_range: [10, 30] #随机删除区域的数量
    hole_height_range: [8, 16] #删除区域的高度范围
    hole_width_range: [8, 16] #删除区域的宽度范围
    fill: [114,114,114] #填充颜色
    p: 0.5

should_flip: True #是否随机翻转
should_draw: True #保存的图片是否有关键框和关键点绘制
flip_prob: 0.5 #随机翻转的概率


# BboxParams 配置
bbox_params:
  format: "yolo"  # 选择 YOLO 格式（你可以选择 coco 或 pascal_voc 等）
  min_visibility: 0.5  # 最小可见度阈值
  label_fields: ['class_labels', 'indexes']


